In [1]:
#Linear Regression on multiple variables
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
Home_Price={
    'area':[2600,3000,3200,3600,4000],
    'bedrooms':[3,4,np.nan,3,5],
    'age':[20,15,18,30,8],
    'price':[550000,565000,610000,595000,760000]
}


In [2]:
df=pd.DataFrame(Home_Price)
print(df)

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000


In [5]:
#price=m1*area+m2*bedrooms+m3*age+b
#price=Dependent variable
#area,bedrooms,age=independent variable
#Taking the missing value as median
import math
median_bedrooms=math.floor(df.bedrooms.median())
print(median_bedrooms)

3


In [6]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df


,area,bedrooms,age,price
0,2600,3.0,20,550000
1,3000,4.0,15,565000
2,3200,3.0,18,610000
3,3600,3.0,30,595000
4,4000,5.0,8,760000


In [7]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [8]:
reg.coef_


array([   137.25, -26025.  ,  -6825.  ])

In [9]:
reg.intercept_

np.float64(383724.99999999994)

In [10]:
reg.predict([[3000,3,40]])


/Users/kpvarma/PycharmProjects/MachineLearning/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [11]:
print(137.25*3000+(-26025.)*3+( -6825.)*40+383724.99999999994)

444399.99999999994


In [12]:
reg.predict([[2500,4,5]])

/Users/kpvarma/PycharmProjects/MachineLearning/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])